// Generated: the name of each day of the 90-day plans (the full texts load on demand).
export type PlanId = 'transformacion' | 'vivir-como-jesus' | 'nueva-mentalidad'

export const PLAN_TITLES: Record<PlanId, string[]> = {
  "transformacion": [
    "Szczery początek",
    "Miłość przed zmianą",
    "Miejsce spotkania",
    "Rozmowa z Ojcem",
    "Modlitwa jednego zdania",
    "Światło na dziś",
    "Pierwszy odpoczynek",
    "Słuchać, nie tylko mówić",
    "Przeżuwać werset",
    "Dziękuję, zanim poproszę",
    "Bóg w codzienności",
    "Przynieść Mu to, co ciąży",
    "Kamienie pamięci",
    "Miłosierdzie każdego poranka",
    "Modlitwa psalmami",
    "Uwielbiać to, kim On jest",
    "Prosić z ufnością",
    "Modlitwa za innych",
    "Gdy brakuje słów",
    "Zachować Słowo",
    "Słowo nie wraca na próżno",
    "Czytać, by wypełniać",
    "Słowo, które widzi",
    "Modlić się Pismem",
    "Czekać na odpowiedź",
    "Modlitwa w domu",
    "Zasnąć w pokoju",
    "Radość w Jego obecności",
    "Najpierw miłość",
    "Wieczorny przegląd dnia",
    "Wyznać po imieniu",
    "Bez potępienia",
    "Nowe serce",
    "Zawrócić",
    "Radość przebaczenia",
    "Jak wschód od zachodu",
    "Łaska, która uczy",
    "Nie walczyć w pojedynkę",
    "Odkładane dobro",
    "Zawsze jest wyjście",
    "Oblec się w Chrystusa",
    "Białe jak śnieg",
    "Puścić kontrolę",
    "Nie moja wola",
    "Połowa drogi",
    "Przerzuć swój ciężar",
    "Pośród ognia",
    "Skarga też jest modlitwą",
    "Wyciszenie przed Bogiem",
    "Wspominać, by ufać",
    "Siły do czekania",
    "On tka dobro",
    "Wystarczy ci moja łaska",
    "Towarzystwo w dolinie",
    "Próba, która kształtuje",
    "Jego pokój cię strzeże",
    "Trwać w winorośli",
    "Owoc Ducha",
    "Wierny w najmniejszym",
    "Pauza w Duchu",
    "Radość, która daje siłę",
    "Przyodziać się w dobroć",
    "Bóg sprawia chęć",
    "Prosty post",
    "Dziesięć minut ciszy",
    "Twoje ciało, Jego świątynia",
    "Strzec tego, na co patrzę",
    "Miłość, którą widać",
    "Pokornie z twoim Bogiem",
    "Owoc nawet w starości",
    "Wdzięczność, która uwielbia",
    "Owoc warg",
    "Twoje dary dla innych",
    "Służyć w ukryciu",
    "Nosić brzemiona",
    "Zachęcać się nawzajem",
    "Trwać we wspólnocie",
    "Opowiedzieć, co uczynił",
    "Modlić się razem",
    "Pocieszać otrzymaną pociechą",
    "Mnie uczyniliście",
    "Uzasadnienie twojej nadziei",
    "Całe życie ofiarą",
    "Jak dobrze razem",
    "Patrząc na Jezusa",
    "Nie ustawaj",
    "Twoja reguła życia",
    "Wysłuchane modlitwy",
    "Wielkie rzeczy uczynił",
    "Z chwały w chwałę"
  ],
  "vivir-como-jesus": [
    "Jezus woła cię dziś",
    "Uczyć się od Niego",
    "Słuchać i czynić",
    "Najważniejsze",
    "Patrzeć ze współczuciem",
    "Dotknąć tego, kogo nikt nie dotyka",
    "Odpocząć z Jezusem",
    "Mali się liczą",
    "Przekroczyć barierę",
    "Przyjąć przed zmianą",
    "Najpierw łaska",
    "Zapytać, zamiast zakładać",
    "Towarzyszyć w bólu",
    "Zostać z Nim",
    "Ubodzy w duchu",
    "Ci, którzy się smucą",
    "Cicha siła",
    "Głód tego, co słuszne",
    "Miłosierdzie na co dzień",
    "Czyste serce",
    "Słuchać i strzec",
    "Czynić pokój",
    "Kiedy dobro kosztuje",
    "Sól, która nadaje smak",
    "Światło w domu",
    "Uczynki, które wskazują na Ojca",
    "Moje błogosławieństwo",
    "Złączeni z winoroślą",
    "Gniew przed snem",
    "Najpierw się pojednaj",
    "Tak — tak, nie — nie",
    "Druga mila",
    "Modlić się za tego, kto mnie rani",
    "Jak słońce",
    "Miłosierni jak Ojciec",
    "Dawać w ukryciu",
    "Gdzie jest twój skarb",
    "Nie sądzić",
    "Najpierw moja część",
    "Złota zasada",
    "Owoc w domu",
    "Dom na skale",
    "W ukryciu",
    "Ojcze nasz",
    "Niech przyjdzie Twoje królestwo",
    "Bądź wola Twoja",
    "Chleb nasz powszedni",
    "Przyjąć i dać przebaczenie",
    "Naucz nas się modlić",
    "Siedemdziesiąt siedem razy",
    "Darowany dług",
    "Przeprosić bez wymówek",
    "Wybaw nas od złego",
    "Prosiłem za tobą",
    "Dobra cząstka",
    "Najpierw królestwo",
    "Ulitował się nad nim",
    "Idź i ty czyń podobnie",
    "Ojciec, który biegnie",
    "Starszy brat",
    "Szukać tej, której brakuje",
    "Boże, bądź miłosierny",
    "Owoc w cierpliwości",
    "Twoje dary w służbie",
    "Życie to nie rzeczy",
    "Dawać z tego, co masz",
    "Zaprosić tego, kto nie odda",
    "Bardzo umiłować",
    "Mnie uczyniliście",
    "Ukryty zaczyn",
    "Umywać nogi",
    "Wielki jest ten, kto służy",
    "Ostatnie miejsce",
    "Jak ja was umiłowałem",
    "Poznani po miłości",
    "Przyjaciele do końca",
    "Pełna radość",
    "Zostańcie ze mną",
    "Uzdrawiać zamiast ranić",
    "Ojcze, przebacz im",
    "Oto twoja matka",
    "Zawołana po imieniu",
    "Iść obok zniechęconych",
    "Pałające serca",
    "Miłujesz mnie?",
    "Tak i ja was posyłam",
    "Moja reguła życia",
    "Postępować tak jak On",
    "W pokoju ze wszystkimi",
    "Z tobą przez wszystkie dni"
  ],
  "nueva-mentalidad": [
    "Umysł, który się odnawia",
    "Policz swoje narzekania",
    "Myśli u korzenia",
    "Zatrzymaj się, nazwij, zmień",
    "Zabiera czy daje życie?",
    "Filtr z Listu do Filipian",
    "Twój pierwszy tydzień",
    "Kłamstwo i prawda",
    "Pierwsza myśl",
    "To, na co patrzysz, cię wypełnia",
    "Spojrzeć z góry",
    "Modlitwa strzała",
    "Zdjąć stare, przyoblec nowe",
    "Bóg kończy to, co zaczyna",
    "Nowe stworzenie",
    "Miłość, na którą nie trzeba zasłużyć",
    "Bez potępienia",
    "Przeszłość nie jest twoim imieniem",
    "Dzieło z celem",
    "Zadziwiająco i cudownie",
    "Chrystus żyje we mnie",
    "Wolność od zabiegania o aprobatę",
    "Kiedy cię krytykują",
    "Mów do siebie z łaską",
    "Moc w słabości",
    "Rany nie są twoim imieniem",
    "Ród wybrany",
    "Twoje nowe imię",
    "Policz jeszcze raz",
    "Trzy podziękowania dziennie",
    "Od narzekania do modlitwy",
    "Wdzięczność za drobiazgi",
    "Wdzięczność wobec ludzi",
    "Wdzięczność w szare dni",
    "Tydzień wdzięczności",
    "Kamienie pamięci",
    "Wdzięczność przy stole",
    "„A co, jeśli…?”",
    "Prosić z dziękczynieniem",
    "Pokój, który strzeże",
    "Kartka trosk",
    "Trzecie liczenie",
    "Tylko na dziś",
    "Umysł oparty na Bogu",
    "Gdy umysł się nie zatrzymuje",
    "Zasnąć w spokoju",
    "Powierzyć swoich bliskich",
    "Lew i niedźwiedź",
    "Otwórz kartkę",
    "Życie w języku",
    "Czym jest pełne serce",
    "Skory do słuchania",
    "Słowa, które budują",
    "Łagodna odpowiedź",
    "Przemów do swojej duszy",
    "Miecz czy lekarstwo",
    "Błogosławić swoich bliskich",
    "Etykiety na dzieciach",
    "Chwalić na głos",
    "Bez drew",
    "Wiadomości z łaską",
    "Straż przy ustach",
    "Inny dom, inne słowa",
    "Twoja własna droga",
    "Czego nie widać na zdjęciu",
    "Nazwać zazdrość",
    "Cieszyć się z innymi",
    "Zadowolenia można się nauczyć",
    "Kiedy już będę mieć…",
    "Miłe dziedzictwo",
    "Ten sam film",
    "Zamknąć zeszyt długów",
    "Pozbyć się goryczy",
    "Zaprzestań gniewu",
    "Bóg obraca to w dobro",
    "Porzucić „trzeba było…”",
    "Dusza w spokoju",
    "Jedna uzda",
    "Więcej niż siła woli",
    "Pieniądze na swoim miejscu",
    "Zarządzać, nie posiadać",
    "Pracować dla Pana",
    "Liczyć swoje dni",
    "Dzieła i zamysły",
    "Nadzieja, którą się wybiera",
    "Boże myśli o tobie",
    "Nieść nadzieję",
    "Twoje nowe zdania",
    "Spójrz na drogę",
    "Nowy umysł"
  ]
}
